### ISSUE TITLE
Error: Processing fasta assembly inputs not successful.

### ISSUE THREAD

**Issue by varunshamanna** [qunfengdong/MicroGMT#1]
./Prepare_fasta.sh: line 25: hCoV-19_India_AP-CCMB-GC41_2020|EPI_ISL_528809|2020-05-29.fa: Invalid argument

I am getting this error in the first step 
i.e 
> python /media/varun/Data_Vol_3/GHRU/Tools/MicroGMT/sequence_to_vcf.py -r /media/varun/Data_Vol_3/GHRU/Tools/MicroGMT/NC_045512_source_files/NC_045512.fa -i assembly -fs hCoV-19IndiaAP-CCMB-GC412020EPI_ISL_5288092020-05-29.fasta -o out

**Comment by YJulyXing** [comment]
Hello,

It looks like your fasta headers have "|" which couldn't be recognized. Could you try to replace "|" by underline or something else using command like
`sed 's/\|/_/g' hCoV-19IndiaAP-CCMB-GC412020EPI_ISL_5288092020-05-29.fasta > name_of_new_file`?

**Comment by varunshamanna** [comment]
> Hello,
> 
> It looks like your fasta headers have "|" which couldn't be recognized. Could you try to replace "|" by underline or something else using command like
> `sed 's/\|/_/g' hCoV-19IndiaAP-CCMB-GC412020EPI_ISL_5288092020-05-29.fasta > name_of_new_file`?

Thanks it worked.
